# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dynamic Digital
email: luke@dynamicdigitalworld.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Dynamic Digital is a news, software and game development company. 
  We are driven by an instinct to provide our customers
  with the best experience that we can and listening to
  our customers to see what they want us to improve upon.
  We have a simple goal to provide the best experience
  we can for our customers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lj-court.github.io/Main-Site/" # the base hostname & protocol for your site, e.g. http://example.com
repository: "LJ-Court.github.io/main-site"

# Build settings
search: true
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.23.0"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap

include: ["_pages"]

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      comments: true
      read_time: true
      share: true
      related: true

# analytics settings

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-K753RQ0V2X"
    anonymize_ip: false # default

# comment settings

comments:
  provider: "disqus"
  disqus:
    shortname: "dynamic-digital"

# footer links

footer:
  links:
    - label: "Privacy Policy"
      url: "/privacy.html"
    - label: "Cookies Policy"
      url: "/cookies.html"
    - label: "Opt Out of Tracking (Google)"
      url: "https://tools.google.com/dlpage/gaoptout/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
#   - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
