backend:
  name: git-gateway
  branch: main
media_folder: 'assets'
publish_mode: editorial_workflow
site_url: https://www.dynamicdigitalworld.co.uk
logo_url: https://www.dynamicdigitalworld.co.uk/assets/AppIcons/windows11/Square44x44Logo.altform-lightunplated_targetsize-40.png
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'string', default: 'single' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { label: 'Header Image', name: 'header.header_image', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'markdown', required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
